# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Open Systems Pharmacology
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Reliable, powerful and easy-to-use modeling &amp; simulation tools for pharmaceutical 
  and other life-sciences applications. Qualified and accepted by the scientific community 
  including academia, regulatory agencies and industry. Available free to everyone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localtest-open-systems-pharmacology.github.io" # the base hostname & protocol for your site, e.g. http://example.com
base: open-systems-pharmacology.org # the base hostname & protocol for your site, e.g. http://example.com
github: https://github.com/localtest-open-systems-pharmacology.github.io
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

collections:
  news:
    output: false
    permalink: /:collection/:name
  examples:
    output: false
    permalink: /:collection/:name
  tutorials:
    output: false
    permalink: /:collection/:name
  publications:
    output: false
    permalink: /:collection/:name
  team:
    output: false
    permalink: /:collection/:name
